name: 'Continuous Integration'

on:
  push:
  pull_request:

jobs:
  terraform:
    name: Terraform build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Lint
        uses: actionshub/terraform-lint@master

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform config
        run: terraform validate
        env:
          AUTH0_CLIENT_ID: test
          AUTH0_CLIENT_SECRET: test
          AWS_REGION: test

      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Plan only on push except to master
      - name: Terraform plan
        if: github.ref != 'refs/heads/master' && github.event_name == 'push'
        run: terraform plan -no-color

      # Apply only on push to master
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve

      ##############
      ## Finalize ##
      ##############
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          branch: auto-terraform-${{github.ref}}
          commit-message: Lint Terraform code
          title: Changes by Terraform action workflow
          labels: automerge, build

      - name: Merge Pull Request
        uses: actions/github-script@master
        if: ${{ steps.cpr.outputs.pull-request-number > 0 }}
        env:
          pr_number: ${{ steps.cpr.outputs.pull-request-number }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: process.env['pr_number']
            })
