name: 'Documentation'

on: push

jobs:
  documentation:
    name: Update documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      ##################################################################
      ## Download generic organization-wide files and Readme sections ##
      ##################################################################
      - name: Config - Markdown linting
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/linters/markdown/.markdownlint.yml

      - name: docs/CONTRIBUTING.md
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/docs/CONTRIBUTING.md
          path: docs

      - name: docs/CODE_OF_CONDUCT.md
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/docs/CODE_OF_CONDUCT.md
          path: docs

      - name: docs/SECURITY.md
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/docs/SECURITY.md
          path: docs

      - name: LICENSE
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/LICENSE

      - name: README.md - Environment variables
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/environment-variables.md
          target: README.md

      - name: README.md - Support
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/support.md
          target: README.md

      - name: README.md - Contributing
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/contribute.md
          target: README.md

      - name: README.md - License
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/license.md
          target: README.md

      - name: README.md - About organization
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/about-org.md
          target: README.md

      ########################################
      ## Terraform specific readme sections ##
      ########################################
      - name: README.md - Terraform backend
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/terraform/backend.md
          target: README.md
          pattern: <!-- auto-terraform-backend -->

      - name: Install terraform-docs
        run: GO111MODULE="on" go get github.com/segmentio/terraform-docs@v0.9.1

      - name: README.md - Variables
        uses: olivr-com/inject-command-action@v1
        with:
          command: $(go env GOPATH)/bin/terraform-docs md ./ --no-header --no-requirements --no-providers --sort-by-required --no-sort | sed -e 's/## Inputs/### Input Variables/' | sed -e 's/## Outputs/### Outputs/'
          target: README.md
          pattern: <!-- auto-terraform-variables -->

      - name: README.md - Terraform environment variables
        uses: olivr-com/inject-command-action@v1
        with:
          command: cat .env.example | perl -p0e 's/export (\w+)=.*/- `$1`/mg' | perl -ne 'print unless /^\#\!\/bin\/bash$/' | perl -p0e 's/^\#\s(.*)$/\#\#\#\# $1\n/mg' | perl -p0e 's/^\#\#\s(.*)$/$1\n/mg'
          target: README.md
          pattern: <!-- auto-terraform-env -->

      ##############
      ## Finalize ##
      ##############
      - name: Markdown Lint
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
          fix: true
          config: .markdownlint.yml

      - name: Cleanup Markdown config
        run: rm -rf .markdownlint.yml

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          branch: auto-documentation-${{github.ref}}
          commit-message: Update documentation
          title: Changes by Documentation action workflow
          labels: automerge, documentation

      - name: Merge Pull Request
        uses: actions/github-script@master
        if: ${{ steps.cpr.outputs.pull-request-number > 0 }}
        env:
          pr_number: ${{ steps.cpr.outputs.pull-request-number }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: process.env['pr_number']
            })
