name: 'Generate Documentation'

on: push

jobs:
  terraform:
    name: Terraform Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Generate documentation for input/output variables
        run: |
          terraform-docs md ./ --no-header --no-requirements --no-providers --sort-by-required --no-sort | sed -e 's/## Inputs/### Input Variables/' | sed -e 's/## Outputs/### Outputs/' | perl -pe 'BEGIN { print "<!-- terraform-docs -->\n\n" }' | perl -pe 'END { print "<!-- terraform-docs -->\n" }' > .temp-documentation
          perl -p0e 's/<!-- terraform-docs -->.*<!-- terraform-docs -->\n/<!-- terraform-docs -->/s' -i README.md
          perl -p0e 's/<!-- terraform-docs -->/`cat .temp-documentation`/ge' -i README.md

      - name: Generate documentation for environment variables
        run: |
          curl -s https://raw.githubusercontent.com/olivr-com/documentation-action/master/terraform/env.md > .temp-documentation-env.md
          cat .env.example | perl -p0e 's/export (\w+)=.*/- `$1`/mg' | perl -ne 'print unless /^\#\!\/bin\/bash$/' | perl -p0e 's/^\#\s(.*)$/\#\#\#\# $1\n/mg' | perl -p0e 's/^\#\#\s(.*)$/$1\n/mg' > .temp-documentation-env-variables
          perl -p0e 's/<!-- env -->/`cat .temp-documentation-env-variables`/ge' -i .temp-documentation-env.md
          perl -p0e 's/<!-- terraform-env-docs -->.*<!-- terraform-env-docs -->\n/<!-- terraform-env-docs -->/s' -i README.md
          perl -p0e 's/<!-- terraform-env-docs -->/`cat .temp-documentation-env.md`/ge' -i README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Update documentation
          branch: ${{ github.head_ref }}
          file_pattern: README.md
