name: 'Lint files'

on: push

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Linting
        uses: actionshub/terraform-lint@master

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Lint Terraform files
          branch: ${{ github.head_ref }}

  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Markdown Linting
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md' --fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Lint files
          branch: ${{ github.head_ref }}
