name: 'Style and documentation'

on: push

jobs:
  main:
    name: Style and documentation
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Lint - Download markdown config
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/linters/markdown/.markdownlint.yml

      - name: Lint - Terraform Format
        run: terraform fmt

      - name: Lint - Terraform
        uses: actionshub/terraform-lint@master

      - name: Docs - About organization
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/about-org.md
          target: README.md

      - name: Docs - License
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/LICENSE

      - name: Docs - License in Readme
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/license.md
          target: README.md

      - name: Docs - Support
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/support.md
          target: README.md
          
      - name: Docs - Contributing
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/docs/CONTRIBUTING.md

      - name: Docs - Contributing in Readme
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/contribute.md
          target: README.md

      - name: Docs - Code of Conduct
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/docs/CODE_OF_CONDUCT.md
          path: docs

      - name: Docs - Security
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/docs/SECURITY.md
          path: docs

      - name: Install Terraform docs
        run: GO111MODULE="on" go get github.com/segmentio/terraform-docs@v0.9.1

      - name: Docs - Terraform input/output
        uses: olivr-com/inject-command-action@v1
        with:
          command: $(go env GOPATH)/bin/terraform-docs md ./ --no-header --no-requirements --no-providers --sort-by-required --no-sort | sed -e 's/## Inputs/### Input Variables/' | sed -e 's/## Outputs/### Outputs/'
          target: README.md
          pattern: <!-- auto-terraform-variables -->

      - name: Docs - Terraform environment variables
        uses: olivr-com/inject-command-action@v1
        with:
          command: cat .env.example | perl -p0e 's/export (\w+)=.*/- `$1`/mg' | perl -ne 'print unless /^\#\!\/bin\/bash$/' | perl -p0e 's/^\#\s(.*)$/\#\#\#\# $1\n/mg' | perl -p0e 's/^\#\#\s(.*)$/$1\n/mg'
          target: README.md
          pattern: <!-- auto-terraform-environment-variables -->
      
      - name: Lint - Markdown
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
          fix: true
          config: .markdownlint.yml

      - name: Lint - Cleanup
        run: rm -rf .markdownlint.yml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Update documentation
          branch: ${{ github.head_ref }}