name: 'Style and documentation'

on: push

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    outputs: 
      new_sha: ${{ steps.sha.outputs.SHA }}   
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Download linting config
        run: |
          wget https://raw.githubusercontent.com/olivr-com/defaults/master/linters/markdown/.markdownlint.yml

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Linting
        uses: actionshub/terraform-lint@master

      - name: Markdown Linting
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
          fix: true
          config: .markdownlint.yml

      - name: Cleanup
        run: rm -rf .markdownlint.yml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Lint files
          branch: ${{ github.head_ref }}

      - name: get sha
        id: sha
        run: echo "::set-output name=SHA::$(git rev-parse HEAD)"
      - run: echo ${{ steps.sha.outputs.SHA }}

  documentation:
    name: Generate documentation
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: ${{ needs.lint.outputs.new_sha }}

      - name: About organization
        run: |
          curl -s https://raw.githubusercontent.com/olivr-com/defaults/master/documentation/about-org.md > .about-org-temp
          perl -p0e 's/<!-- auto-about-org -->.*<!-- auto-about-org -->\n/<!-- auto-about-org -->/s' -i README.md
          perl -p0e 's/<!-- auto-about-org -->/`cat .about-org-temp`/ge' -i README.md
          rm -rf .about-org-temp

      - name: Terraform input/output
        run: |
          GO111MODULE="on" go get github.com/segmentio/terraform-docs@v0.9.1
          $(go env GOPATH)/bin/terraform-docs md ./ --no-header --no-requirements --no-providers --sort-by-required --no-sort | sed -e 's/## Inputs/### Input Variables/' | sed -e 's/## Outputs/### Outputs/' | perl -pe 'BEGIN { print "<!-- auto-terraform-variables -->\n\n" }' | perl -pe 'END { print "<!-- auto-terraform-variables -->\n" }' > auto-terraform-variables-temp
          perl -p0e 's/<!-- auto-terraform-variables -->.*<!-- auto-terraform-variables -->\n/<!-- auto-terraform-variables -->/s' -i README.md
          perl -p0e 's/<!-- auto-terraform-variables -->/`cat auto-terraform-variables-temp`/ge' -i README.md
          rm -rf auto-terraform-variables-temp

      - name: Terraform environment variables
        run: |
          curl -s https://raw.githubusercontent.com/olivr-com/defaults/master/documentation/terraform/environment-variables.md > environment-variables-temp
          cat .env.example | perl -p0e 's/export (\w+)=.*/- `$1`/mg' | perl -ne 'print unless /^\#\!\/bin\/bash$/' | perl -p0e 's/^\#\s(.*)$/\#\#\#\# $1\n/mg' | perl -p0e 's/^\#\#\s(.*)$/$1\n/mg' > vars-temp
          perl -p0e 's/<!-- env -->/`cat vars-temp`/ge' -i environment-variables-temp
          perl -p0e 's/<!-- auto-terraform-environment-variables -->.*<!-- auto-terraform-environment-variables -->\n/<!-- auto-terraform-environment-variables -->/s' -i README.md
          perl -p0e 's/<!-- auto-terraform-environment-variables -->/`cat environment-variables-temp`/ge' -i README.md
          rm -rf environment-variables-temp vars-temp

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Update documentation
          branch: ${{ github.head_ref }}
          file_pattern: README.md