name: 'Build'

on:
  push:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - run: terraform init

      - name: Validate Terraform config
        run: terraform validate
        env:
          AUTH0_CLIENT_ID: test
          AUTH0_CLIENT_SECRET: test
          AWS_REGION: test

      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color

      # Comment with plan result if on pull request
      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          STDOUT: '```${{ steps.plan.outputs.stdout }}```'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.STDOUT
            })

      # Apply only on master
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve
