name: 'Terraform Validation'

on: [push, pull_request]

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Checkout
        uses: actions/checkout@master

      - run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Linting
        uses: actionshub/terraform-lint@master

      - name: Terraform Security Scan
        uses: triat/terraform-security-scan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Lint Terraform
          branch: ${{ github.head_ref }}
